### ISSUE TITLE
Commits counts not working

### ISSUE THREAD

**Issue by tchx84** [blackducksoftware/ohloh-ui#1438]
I noticed that the commit count is currently not working.

The most visible example is https://www.openhub.net, on the "Most Active Contributors" section you can clearly see that these numbers are not accurate as they would have thousands of commits not just two.

Also, on profile pages, the total count does not reflect the same amount of commits reflected at the graph below.

**Comment by PDegenPortnoy** [comment]
Thanks for bringing this to our attention. There is a known issue that we've been tracking about Commit counts. More details are in the Forums: https://www.openhub.net/topics/14956

We believe we have found the root cause and did some work to clean up the site and are now working on a systemic fix. We'll take a look at the home page and see if we can't get those numbers updated.

**Comment by PDegenPortnoy** [comment]
@tchx84 We believe we have addressed the root issues that had caused this problem. Thanks for bringing it to our attention.
