### ISSUE TITLE
Login buttons do not work with Firefox

### ISSUE THREAD

**Issue by intgr** [blackducksoftware/ohloh-ui#1465]
I am unable to log in using Firefox Developer Edition 73.0b9, on neither Linux nor macOS. But this is not specific to the Firefox version, this issue has been occuring for a bit already. Also tested with a clean Firefox profile with no extensions.

I can get to the page https://www.openhub.net/sessions/new, but from there on the "Sign in with [...]" buttons do not go anywhere.

Nor does the "Agree" button on the cookie notice do anything.

**Comment by PDegenPortnoy** [comment]
Hi, thanks for documenting this. We are aware of the issue and suspect that there may be a few potential causes. One is that we put the Open Hub behind a WAF that seems to be changing the content we're serving. Another is that Firefox and Safari are blocking tracking javascript by default and this may also be changing the javascript behavior across the site. We have a Blocker ticket upon which we are working to address these issues.

This issue is also being tracked at https://github.com/webcompat/web-bugs/issues/47751

**Comment by intgr** [comment]
Thanks! I've subscribed to the issue in webcompat. It's up to you if you want to keep this issue here open or not.

**Comment by PDegenPortnoy** [comment]
We believe this issue is resolved. We've made some configuration changes to our WAF and verified that previously affected buttons are once again working as expected.
